ScienceBlogs/Areas/AdminPanel/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScienceBlogs.Models;
using Microsoft.AspNetCore.Hosting;

namespace ScienceBlogs.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class BlogsController : Controller
    {
        private readonly BlogsContext _context;
		private readonly IWebHostEnvironment _hostEnvironment;
		public BlogsController(BlogsContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
			this._hostEnvironment = hostEnvironment;

		}

        // GET: AdminPanel/Blogs
        public async Task<IActionResult> Index()
        {
            var blogsContext = _context.Blogs.Include(b => b.Category);
            return View(await blogsContext.ToListAsync());
        }

        // GET: AdminPanel/Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: AdminPanel/Blogs/Create
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name");
            return View();
        }

        // POST: AdminPanel/Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Description,Date,Topic,CategoryID,Author,file")] Blog blog)
        {
            if (ModelState.IsValid)
            {

				//save image to wwwroot/Images/Blogs
				string wwwRootPath = _hostEnvironment.WebRootPath;
				string fileName = Path.GetFileNameWithoutExtension(blog.file.FileName);
				string extension = Path.GetExtension(blog.file.FileName);
				blog.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
				string path = Path.Combine(wwwRootPath + "/Images/Blogs/", fileName);
				using (var fileStream = new FileStream(path, FileMode.Create))
				{
					await blog.file.CopyToAsync(fileStream);

				}

				_context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name", blog.CategoryID);
            return View(blog);
        }
   
        // GET: AdminPanel/Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name", blog.CategoryID);
            return View(blog);
        }

        // POST: AdminPanel/Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Description,Date,Topic,CategoryID,Author,file")] Blog blog)
        {
            if (id != blog.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
					//save image to wwwroot/Images/Blogs
					string wwwRootPath = _hostEnvironment.WebRootPath;
					string fileName = Path.GetFileNameWithoutExtension(blog.file.FileName);
					string extension = Path.GetExtension(blog.file.FileName);
					blog.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
					string path = Path.Combine(wwwRootPath + "/Images/Blogs/", fileName);
					using (var fileStream = new FileStream(path, FileMode.Create))
					{
						await blog.file.CopyToAsync(fileStream);

					}

					_context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name", blog.CategoryID);
            return View(blog);
        }

        // GET: AdminPanel/Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: AdminPanel/Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Blogs == null)
            {
                return Problem("Entity set 'BlogsContext.Blogs'  is null.");
            }
            var blog = await _context.Blogs.FindAsync(id);
            if (blog != null)
            {
				//delete image from wwwroot/Images/Blogs
				var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "Images/Blogs", blog.Image);
				if (System.IO.File.Exists(imagePath))
					System.IO.File.Delete(imagePath);

				_context.Blogs.Remove(blog);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
          return _context.Blogs.Any(e => e.ID == id);
        }
    }
}

ScienceBlogs/Areas/AdminPanel/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScienceBlogs.Models;
using Microsoft.AspNetCore.Hosting;

namespace ScienceBlogs.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly BlogsContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

		public CategoriesController(BlogsContext context,IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
		}

        // GET: AdminPanel/Categories
        public async Task<IActionResult> Index()
        {
              return View(await _context.Categories.ToListAsync());
        }

        // GET: AdminPanel/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: AdminPanel/Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminPanel/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,File")] Category category)
        {
            if (ModelState.IsValid)
            {
				//save image to wwwroot/Images/Categories
				string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(category.File.FileName);
                string extension = Path.GetExtension(category.File.FileName);
				category.Image =fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Images/Categories/", fileName);
                using(var fileStream = new FileStream(path,FileMode.Create))
                {
                    await category.File.CopyToAsync(fileStream);

				}

				_context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        // GET: AdminPanel/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: AdminPanel/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description,File")] Category category)
        {
            if (id != category.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
					//save image to wwwroot/Images/Categories
					string wwwRootPath = _hostEnvironment.WebRootPath;
					string fileName = Path.GetFileNameWithoutExtension(category.File.FileName);
					string extension = Path.GetExtension(category.File.FileName);
					category.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
					string path = Path.Combine(wwwRootPath + "/Images/Categories/", fileName);
					using (var fileStream = new FileStream(path, FileMode.Create))
					{
						await category.File.CopyToAsync(fileStream);

					}

					_context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: AdminPanel/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: AdminPanel/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'BlogsContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                //delete image from wwwroot/Images/Categories
                var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "Images/Categories", category.Image);
                if (System.IO.File.Exists(imagePath))
                    System.IO.File.Delete(imagePath);

				_context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return _context.Categories.Any(e => e.ID == id);
        }
    }
}

ScienceBlogs/Areas/AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfCore2C</title>
    <link rel="stylesheet" href="~/Admin/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Admin/css/site.css" />
    <link rel="stylesheet" href="~/Admin/css/all.min.css" />
    <link rel="stylesheet" href="~/Admin/css/framework.css" />
    <link rel="stylesheet" href="~/Admin/css/master.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;500&display=swap" rel="stylesheet" />
</head>
<body>
    <div class="page d-flex">
        <div class="sidebar bg-white p-20 p-relative">
            <h4 class="p-relative txt-c mt-0">
                <a style="text-decoration:none;color:black" asp-area="" asp-controller="Home" asp-action="Index">Science Blog</a>
            </h4>
            <ul>
                <li>
                    <a class="active d-flex align-center fs-14 c-black rad-6 p-10" asp-area="AdminPanel" asp-controller="Categories" asp-action="Index">
                        <i class="fa-regular fa-newspaper fa-fw"></i>
                        <span>Categories</span>
                    </a>
                </li>
                <li>
                    <a class="d-flex align-center fs-14 c-black rad-6 p-10" asp-area="AdminPanel" asp-controller="Blogs" asp-action="Index">
                        <i class="fa-regular fa-newspaper fa-fw"></i>
                        <span>Blogs</span>
                    </a>
                </li>

            </ul>
        </div>
        <div class="content w-full">
            <div class="head bg-white p-15 between-flex">
                <div class="p-relative">
                    <div class="container">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="icons d-flex align-center">
                    <ul class="navbar-nav ml-auto">
                        
                        <li class="nav-item">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button style="margin-left:5px;" type="submit" class="nav-link btn btn-primary text-light ">Logout</button>
                            </form>
                        </li>
                        
                    </ul>
                </div>
            </div>

            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>

    </div>
    <script src="~/Admin/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Admin/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Admin/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>